// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'div1': string;
  'div2': string;
  'home': string;
  'left': string;
  'right': string;
  'subTitle': string;
  'textBox': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
