// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cases': string;
  'content': string;
  'imgBox': string;
  'subTitle': string;
  'title': string;
  'titleBox': string;
  'top': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
