// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  btn: string;
  div1: string;
  div2: string;
  div3: string;
  div4: string;
  form: string;
}
export const cssExports: CssExports;
export default cssExports;
