// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  date: string;
  imgBox: string;
  line: string;
  news: string;
  p1: string;
  textBox: string;
  title: string;
  wrapper: string;
}
export const cssExports: CssExports;
export default cssExports;
