// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'box': string;
  'copyright': string;
  'footer': string;
  'item': string;
  'list': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
