// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  box: string;
  comName: string;
  copyright: string;
  footer: string;
  img1: string;
  img2: string;
  img3: string;
  imgBox: string;
  item: string;
  list: string;
  title: string;
}
export const cssExports: CssExports;
export default cssExports;
